/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as SoonSlugRouteImport } from './routes/soon.$slug'
import { Route as SoonOurMissionRouteImport } from './routes/soon.our-mission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonSlugRoute = SoonSlugRouteImport.update({
  id: '/soon/$slug',
  path: '/soon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonOurMissionRoute = SoonOurMissionRouteImport.update({
  id: '/soon/our-mission',
  path: '/soon/our-mission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/platform': typeof PlatformRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/soon/$slug': typeof SoonSlugRoute
  '/soon/our-mission': typeof SoonOurMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/platform': typeof PlatformRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/soon/$slug': typeof SoonSlugRoute
  '/soon/our-mission': typeof SoonOurMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/platform': typeof PlatformRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/soon/$slug': typeof SoonSlugRoute
  '/soon/our-mission': typeof SoonOurMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/platform'
    | '/dashboard/$role'
    | '/soon/$slug'
    | '/soon/our-mission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/platform'
    | '/dashboard/$role'
    | '/soon/$slug'
    | '/soon/our-mission'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/platform'
    | '/dashboard/$role'
    | '/soon/$slug'
    | '/soon/our-mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlatformRoute: typeof PlatformRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  SoonSlugRoute: typeof SoonSlugRoute
  SoonOurMissionRoute: typeof SoonOurMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon/$slug': {
      id: '/soon/$slug'
      path: '/soon/$slug'
      fullPath: '/soon/$slug'
      preLoaderRoute: typeof SoonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soon/our-mission': {
      id: '/soon/our-mission'
      path: '/soon/our-mission'
      fullPath: '/soon/our-mission'
      preLoaderRoute: typeof SoonOurMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlatformRoute: PlatformRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  SoonSlugRoute: SoonSlugRoute,
  SoonOurMissionRoute: SoonOurMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
